---
# file: roles/common/tasks/main.yml
- name: NTP must be installed
  become: true
  apt:
    name: ntp
    state: present
  tags: ntp

- name: NTP must be configured
  become: true
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntp
  tags: ntp

- name: NTP must be running
  service:
    name: ntp
    state: started
    enabled: yes
  tags: ntp
