- name: Install apt package requirements
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - software-properties-common
    - apt-transport-https
    - gpg-agent
    - curl
    - procps
    - net-tools
    - gnupg

- name: Install Grafana
  block:
    - name: Import Grafana GPG Key
      ansible.builtin.shell: "wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -"
    - name: Add Grafana Apt Repository
      ansible.builtin.apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
    - name: Install Grafana package
      ansible.builtin.apt:
        name: grafana
        state: present

- name: Enable and start Grafana-Server service
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: Install influxdb package
  ansible.builtin.apt:
    name: influxdb
    state: present