- hosts: elasticsearch
  roles:
    - role: common
    - role: elasticsearch
      vars:
        elasticsearch_network_host: weu-elk-elastic1
        elasticsearch_cluster_name: michel-development
        elasticsearch_elastic_password: Not5ecure!
    - role: kibana
    - role: logstash
      vars:
        elasticsearch_elastic_password: Not5ecure!