---
- hosts: elasticsearch
  tasks:
  - name: stop kibana
    service:
      name: kibana
      state: stopped
  - name: stop elasticsearch
    service:
      name: elasticsearch
      state: stopped
  - name: stop logstash
    service:
      name: logstash
      state: stopped

