- name: Run Elasticsearch Create Enrollment Token Command
  shell: /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana
  register: token_response

- name: Extract Token from Response
  set_fact:
    enrollment_token: "{{ token_response.stdout }}"

- name: Run Kibana Enrollment Token Command
  shell: /usr/share/kibana/bin/kibana-setup --enrollment-token {{ enrollment_token }}
  args:
    stdin: "y\n"

- name: Ensure server.host 0.0.0.0 is set in kibana.yml
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#?server\.host: 0.0.0.0'
    line: 'server.host: 0.0.0.0'
    state: present

- name: Enable and start kibana service
  service:
    name: kibana
    state: started
    enabled: yes