- name: Copy Logstash Output Configuration
  ansible.builtin.template:
    src: 30-elasticsearch-output.conf.j2
    dest: /etc/logstash/conf.d/30-elasticsearch-output.conf
    mode: 0640
    owner: logstash
    group: logstash

- name: Copy Logstash Input Configuration
  ansible.builtin.template:
    src: 02-beats-input.conf.j2
    dest: /etc/logstash/conf.d/02-beats-input.conf
    mode: 0640
    owner: logstash
    group: logstash

- name: Ensures /etc/logstash/config/ dir exists
  file: 
    path: "/etc/logstash/config/"
    state: directory

- name: Ensures /etc/logstash/config/certs dir exists
  file: 
    path: "/etc/logstash/config/certs"
    state: directory

- name: Copy Elastic CA certificate to Logstash folder
  ansible.builtin.copy:
    src: /etc/elasticsearch/certs/http_ca.crt
    dest: /etc/logstash/config/certs/http_ca.crt
    remote_src: yes
    owner: root
    group: root
    mode: '0644'

- name: Enable and start logstash service
  service:
    name: logstash
    state: restarted
    enabled: yes